Script started on Fri 31 Aug 2018 12:52:52 AM CDT
[?1034hbash-4.2$ man ls
[?1049h[?1h=LS(1)                                       User Commands                                       LS(1)[m
[m
[1mNAME[0m[m
       ls - list directory contents[m
[m
[1mSYNOPSIS[0m[m
       [1mls[0m [[4mOPTION[24m]... [[4mFILE[24m]...[m
[m
[1mDESCRIPTION[0m[m
       List  information about the FILEs (the current directory by default).  Sort entries alphabeti‐[m
       cally if none of [1m-cftuvSUX[0m nor [1m--sort[0m is specified.[m
[m
       Mandatory arguments to long options are mandatory for short options too.[m
[m
       [1m-a[0m, [1m--all[0m[m
              do not ignore entries starting with .[m
[m
       [1m-A[0m, [1m--almost-all[0m[m
              do not list implied . and ..[m
[m
       [1m--author[0m[m
              with [1m-l[0m, print the author of each file[m
[m
[7m Manual page ls(1) line 1 (press h for help or q to quit)[27m[K[K[?1l>[?1049lbash-4.2$ man man
[?1049h[?1h=MAN(1)                                    Manual pager utils                                   MAN(1)[m
[m
[1mNAME[0m[m
       man - an interface to the on-line reference manuals[m
[m
[1mSYNOPSIS[0m[m
       [1mman[0m  [[1m-C[0m  [4mfile[24m]  [[1m-d[0m] [[1m-D[0m] [[1m--warnings[0m[=[4mwarnings[24m]] [[1m-R[0m [4mencoding[24m] [[1m-L[0m [4mlocale[24m] [[1m-m[0m [4msystem[24m[,...]][m
       [[1m-M[0m [4mpath[24m] [[1m-S[0m [4mlist[24m] [[1m-e[0m  [4mextension[24m]  [[1m-i[0m|[1m-I[0m]  [[1m--regex[0m|[1m--wildcard[0m]  [[1m--names-only[0m]  [[1m-a[0m]  [[1m-u[0m][m
       [[1m--no-subpages[0m]  [[1m-P[0m [4mpager[24m] [[1m-r[0m [4mprompt[24m] [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m--no-hyphenation[0m] [[1m--no-justifica‐[0m[m
       [1mtion[0m] [[1m-p[0m [4mstring[24m] [[1m-t[0m] [[1m-T[0m[[4mdevice[24m]] [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]] [[1m-Z[0m] [[[4msection[24m] [4mpage[24m ...] ...[m
       [1mman[0m [1m-k[0m [[4mapropos[24m [4moptions[24m] [4mregexp[24m ...[m
       [1mman[0m [1m-K[0m [[1m-w[0m|[1m-W[0m] [[1m-S[0m [4mlist[24m] [[1m-i[0m|[1m-I[0m] [[4m--regex[24m] [[4msection[24m] [4mterm[24m ...[m
       [1mman[0m [1m-f[0m [[4mwhatis[24m [4moptions[24m] [4mpage[24m ...[m
       [1mman[0m [1m-l[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [[1m--warnings[0m[=[4mwarnings[24m]] [[1m-R[0m [4mencoding[24m] [[1m-L[0m [4mlocale[24m]  [[1m-P[0m  [4mpager[24m]  [[1m-r[0m[m
       [4mprompt[24m] [[1m-7[0m] [[1m-E[0m [4mencoding[24m] [[1m-p[0m [4mstring[24m] [[1m-t[0m] [[1m-T[0m[[4mdevice[24m]] [[1m-H[0m[[4mbrowser[24m]] [[1m-X[0m[[4mdpi[24m]] [[1m-Z[0m] [4mfile[24m ...[m
       [1mman[0m [1m-w[0m|[1m-W[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [1m-c[0m [[1m-C[0m [4mfile[24m] [[1m-d[0m] [[1m-D[0m] [4mpage[24m ...[m
       [1mman[0m [[1m-?V[0m][m
[m
[1mDESCRIPTION[0m[m
       [1mman[0m  is  the  system's manual pager. Each [4mpage[24m argument given to [1mman[0m is normally the name of a[m
       program, utility or function.  The [4mmanual[24m [4mpage[24m associated with each of these arguments is then[m
       found  and  displayed. A [4msection[24m, if provided, will direct [1mman[0m to look only in that [4msection[24m of[m
[7m Manual page man(1) line 1 (press h for help or q to quit)[27m[K[K[?1l>[?1049lbash-4.2$ cd c[K[K
bash-4.2$ cd comp3500/project1/
bash-4.2$ ls[K[Kpwd
/home/u2/yzw0060/comp3500/project1
bash-4.2$ ls
commands2.script  gdb.script	  lspci.txt    pipe.script    simple.c
commands.script   git.script	  meminfo.txt  sample.script  test.txt
cpuinfo.txt	  interrupts.txt  nothing      simple	      typescript
bash-4.2$ mkdir i[Kdir1
bash-4.2$ cp nothind[Kg dir1
bash-4.2$ mv tyo[Kpescript dir1
bash-4.2$ cd dir1
bash-4.2$ ls
nothing  typescript
bash-4.2$ rm nothing 
bash-4.2$ cd ..
bash-4.2$ mkdir r[Kdir2
bash-4.2$ rmdir dir2
bash-4.2$ ls
commands2.script  dir1	      interrupts.txt  nothing	     simple
commands.script   gdb.script  lspci.txt       pipe.script    simple.c
cpuinfo.txt	  git.script  meminfo.txt     sample.script  test.txt
bash-4.2$ chmod 754 [K[K[K[K[K[K[K[K[K[Kcd sir1
bash: cd: sir1: No such file or directory
bash-4.2$ cd dir1
bash-4.2$ chmod 754 n[Ktypescript 
bash-4.2$ clear
[3;J[H[2Jbash-4.2$ top
[?1h=[?25l[H[2J(B[mtop - 00:55:33 up 7 days, 16:01,  5 users,  load average: 0.00, 0.01, 0.05(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 376 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 375 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  0.6 (B[m[39;49mus,(B[m[39;49m[1m  1.7 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m 97.8 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m 24510024 (B[m[39;49mtotal,(B[m[39;49m[1m 19799836 (B[m[39;49mfree,(B[m[39;49m[1m  1358576 (B[m[39;49mused,(B[m[39;49m[1m  3351612 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 22568600 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K
[7m  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                             (B[m[39;49m[K
(B[m[1m 2438 yzw0060   20   0  168580   2520   1636 R  14.3  0.0   0:00.06 top                                 (B[m[39;49m[K
(B[m    1 root      20   0  194680   7908   4168 S   0.0  0.0   2:58.54 systemd                             (B[m[39;49m[K
(B[m    2 root      20   0       0      0      0 S   0.0  0.0   0:00.39 kthreadd                            (B[m[39;49m[K
(B[m    3 root      20   0       0      0      0 S   0.0  0.0   0:00.17 ksoftirqd/0                         (B[m[39;49m[K
(B[m    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H                        (B[m[39;49m[K
(B[m    8 root      rt   0       0      0      0 S   0.0  0.0   0:00.13 migration/0                         (B[m[39;49m[K
(B[m    9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                              (B[m[39;49m[K
(B[m   10 root      20   0       0      0      0 S   0.0  0.0   1:48.54 rcu_sched                           (B[m[39;49m[K
(B[m   11 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain                       (B[m[39;49m[K
(B[m   12 root      rt   0       0      0      0 S   0.0  0.0   0:07.19 watchdog/0                          (B[m[39;49m[K
(B[m   13 root      rt   0       0      0      0 S   0.0  0.0   0:01.56 watchdog/1                          (B[m[39;49m[K
(B[m   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.13 migration/1                         (B[m[39;49m[K
(B[m   15 root      20   0       0      0      0 S   0.0  0.0   0:00.28 ksoftirqd/1                         (B[m[39;49m[K
(B[m   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H                        (B[m[39;49m[K
(B[m   19 root      rt   0       0      0      0 S   0.0  0.0   0:01.49 watchdog/2                          (B[m[39;49m[K
(B[m   20 root      rt   0       0      0      0 S   0.0  0.0   0:00.56 migration/2                         (B[m[39;49m[K
(B[m   21 root      20   0       0      0      0 S   0.0  0.0   0:00.18 ksoftirqd/2                         (B[m[39;49m[K[H(B[mtop - 00:55:36 up 7 days, 16:01,  5 users,  load average: 0.00, 0.01, 0.05(B[m[39;49m(B[m[39;49m[K

%Cpu(s):(B[m[39;49m[1m  0.0 (B[m[39;49mus,(B[m[39;49m[1m  0.0 (B[m[39;49msy,(B[m[39;49m[1m  0.0 (B[m[39;49mni,(B[m[39;49m[1m100.0 (B[m[39;49mid,(B[m[39;49m[1m  0.0 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem :(B[m[39;49m[1m 24510024 (B[m[39;49mtotal,(B[m[39;49m[1m 19799852 (B[m[39;49mfree,(B[m[39;49m[1m  1358552 (B[m[39;49mused,(B[m[39;49m[1m  3351620 (B[m[39;49mbuff/cache(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m 12386300 (B[m[39;49mtotal,(B[m[39;49m[1m 12386300 (B[m[39;49mfree,(B[m[39;49m[1m        0 (B[m[39;49mused.(B[m[39;49m[1m 22568616 (B[m[39;49mavail Mem (B[m[39;49m(B[m[39;49m[K
[K

(B[m[1m 2438 yzw0060   20   0  168548   2648   1688 R   0.7  0.0   0:00.08 top                                 (B[m[39;49m[K















[?1l>[25;1H
[?12l[?25h[Kbash-4.2$ who
kjs0034  pts/0        2018-08-30 20:54 (ettin.eng.auburn.edu)
yzw0060  pts/2        2018-08-30 23:42 (ettin.eng.auburn.edu)
yzw0060  pts/4        2018-08-31 00:52
jzb0128  pts/5        2018-08-30 23:48 (ettin.eng.auburn.edu)
rch0012  pts/6        2018-08-30 16:35 (:1)
bash-4.2$ nproc
16
bash-4.2$ exit
exit

Script done on Fri 31 Aug 2018 12:55:49 AM CDT
